apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminpanel
  namespace: rafflethor
spec:
  selector:
    matchLabels:
      app: rafflethor
      tier: adminpanel
  replicas: 1
  template:
    metadata:
      labels:
        app: rafflethor
        tier: adminpanel
    spec:
      containers:
      - image: rafflethor-docker-rafflethor.bintray.io/admin-panel:1.0.3
        name: adminpanel
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: adminpanel
  namespace: rafflethor
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: rafflethor
    tier: adminpanel
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: adminpanel
  namespace: rafflethor
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: adminpanel.services.rafflethor.io
    http:
      paths:
      - path: /
        backend:
          serviceName: adminpanel
          servicePort: 80
