apiVersion: v1
kind: ServiceAccount
metadata:
  name: travis-echo
  namespace: rafflethor
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: rafflethor
  name: travis-deploy-role
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["set", "get", "create", "apply", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "apply", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "apply", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "apply", "update"]
- apiGroups: ["extensions", "apps"]
  resources: ["ingresses"]
  verbs: ["get", "create", "apply", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: travis-role-binding
  namespace: rafflethor
subjects:
- kind: ServiceAccount
  name: travis-echo
  namespace: rafflethor
roleRef:
  kind: Role
  name: travis-deploy-role
  apiGroup: rbac.authorization.k8s.io
